### ISSUE TITLE
Work with Rails 4.0.1?

### ISSUE THREAD

**Issue by MentalPower** [ReneB/activerecord-like#2]
Hi there,

I found your project after a Google search on how to do like queries in rails. I tried to install the gem by adding it to my Gemfile (and running bundle), but I get this error no matter how I try to use it:

```
 undefined method `like' for #<ActiveRecord::QueryMethods::WhereChain:0x007f975938b218>
```

My current usage is something like this:

``` ruby
scope :live, -> {
    where.like(qualifier_5: 'Live%')
}
```

but even something as simple as this still fails:

``` ruby
Schedule.where.like(qualifier_5: 'Live%')
```

Any ideas?
